class Autogenerated {
  List<Fuels>? fuels;
  String? fuelPrice;

  Autogenerated({this.fuels, this.fuelPrice});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      fuels: json['fuels'] != null
          ? List<Fuels>.from(json['fuels'].map((v) => Fuels.fromJson(v)))
          : null,
      fuelPrice: json['fuelPrice'],
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (fuels != null) {
      data['fuels'] = fuels!.map((v) => v.toJson()).toList();
    }
    data['fuelPrice'] = fuelPrice;
    return data;
  }
}

class Fuels {
  String? type;
  List<Price>? price;
  String? updatedAt;

  Fuels({this.type, this.price, this.updatedAt});

  factory Fuels.fromJson(Map<String, dynamic> json) {
    return Fuels(
      type: json['type'],
      price: json['price'] != null
          ? List<Price>.from(json['price'].map((v) => Price.fromJson(v)))
          : null,
      updatedAt: json['updatedAt'],
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['type'] = type;
    if (price != null) {
      data['price'] = price!.map((v) => v.toJson()).toList();
    }
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class Price {
  double? value;
  String? currency;
  String? currencySymbol;
  String? volumeUnit;

  Price({this.value, this.currency, this.currencySymbol, this.volumeUnit});

  factory Price.fromJson(Map<String, dynamic> json) {
    return Price(
      value: json['value']?.toDouble(), // Parse value to double
      currency: json['currency'],
      currencySymbol: json['currencySymbol'],
      volumeUnit: json['volumeUnit'],
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['value'] = value;
    data['currency'] = currency;
    data['currencySymbol'] = currencySymbol;
    data['volumeUnit'] = volumeUnit;
    return data;
  }
}