name: Automatic Label Sync

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  label_sync:
    name: Automatic Label Synchronization
    uses: compairifuel/.github/.github/workflows/reusable-labelsync.yml@main
    permissions:
      contents: read
      issues: write
